INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("project one", "category one", 1000, "1/1/2020", "12/31/20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("project two", "category two", 2000, "1/2/2020", "12/30/20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("project three", "category three", 3000, "1/3/2020", "12/29/20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("project four", "category four", 4000, "1/4/2020", "12/28/20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("project five", "category five", 5000, "1/5/2020", "12/27/20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("project six", "category six", 6000, "1/6/2020", "12/26/20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("project seven", "category seven", 7000, "1/7/2020", "12/25/20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("project eight", "category eight", 8000, "1/8/2020", "12/24/20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("project nine", "category one", 3000, "1/1/2020", "12/31/20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("project ten", "category one", 1000, "1/1/2020", "12/31/20");

INSERT INTO users (name, age) VALUES ("name1", 26);
INSERT INTO users (name, age) VALUES ("name2", 27);
INSERT INTO users (name, age) VALUES ("name3", 28);
INSERT INTO users (name, age) VALUES ("name4", 29);
INSERT INTO users (name, age) VALUES ("name5", 30);
INSERT INTO users (name, age) VALUES ("name6", 29);
INSERT INTO users (name, age) VALUES ("name7", 27);
INSERT INTO users (name, age) VALUES ("name8", 31);
INSERT INTO users (name, age) VALUES ("name9", 26);
INSERT INTO users (name, age) VALUES ("name0", 24);
INSERT INTO users (name, age) VALUES ("name11", 26);
INSERT INTO users (name, age) VALUES ("name12", 25);
INSERT INTO users (name, age) VALUES ("name13", 22);
INSERT INTO users (name, age) VALUES ("name14", 29);
INSERT INTO users (name, age) VALUES ("name15", 29);
INSERT INTO users (name, age) VALUES ("name16", 27);
INSERT INTO users (name, age) VALUES ("name17", 35);
INSERT INTO users (name, age) VALUES ("name18", 41);
INSERT INTO users (name, age) VALUES ("name19", 50);
INSERT INTO users (name, age) VALUES ("name10", 33);

INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 2, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 3, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 4, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 5, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 6, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 7, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 8, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 9, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 10, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 1, 11);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 2, 12);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 1, 13);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 3, 14);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 1, 15);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 4, 16);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 1, 17);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 5, 18);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 1, 19);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 6, 20);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 7, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 8, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 1, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 9, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 1, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 10, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 1, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 2, 9);
